version: "2"
services:
  webapi:
    container_name: webapi
    restart: always
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/webapi
    network_mode: host

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    network_mode: host
  